[workspace]
members = ["crates/*"]

[workspace.package]
name = "lemmy-markdown-it-plugins"
edition = "2021"

[workspace.dependencies]
markdown-it = { version = "0.6", default-features = false }
rstest = "0.22.0"
